Cartographer3D/cartographer-klipper

- cartographer.py
Implement Change by @mattthebaker from Beacon3D GPL code to avoide Z_TILT and QGL macro issues
> probe: fix breaking inteface change in mainline.

- cartographer.py
@RichardTHF   gave this to me on discord and asked for submit i dont have write access
> Fix agains klipper3d commit 1591a51f76cff336f0109bf4459bfa46dca1eaa3

- scanner.py
added the same debug output to threshold test. But even the original from Chris is crashing while trying to write the plot
> Output csv results - as well for threshold_test

- scanner.py
`CARTOGRAPHER_TOUCH` updated to display what retry user is currently at via the console.
Signed-off-by: Chris Krause <krause3284@gmail.com
> fix: CARTOGRAPHER_TOUCH output to display retry attempt numbers

- scanner.py
Output of `CARTOGRAPHER_TOUCH` updated to use rounded format making them easier to read.
Signed-off-by: Chris Krause <krause3284@gmail.com
> fix: rounded long digits to 4 decimals in CARTOGRAPHER_TOUCH

- scanner.py
> feature: TEMPERATURE_WAIT instead of m109

- scanner.py
Fixes silly bug that wouldnt increase temp..
> fix set temp not increasing temp

- firmware.sh
Firmware flasher will no longer `git pull` this repo and will instead download the latest files from master into a /tmp directory and then use that to get files to update without updating the main repo and ruining peoples installs.
optional `-b beta` flag when using the firmware flasher script for pulling from the `beta-firmware` branch, which we will store firmware for testing until release.
> flasher will now pull from github into /tmp

- firmware.sh
Just applies formatting rules.
> Run shfmt on firmware.sh

- firmware.sh
Repurpose the -b flag to take any commitish.
This allows us to do `firmware.sh -b beta` to pull beta branch firmware.
We can also do `firmware.sh -b develop` or even `firmware.sh -b v1.0.1`
> Use firmware flasher to flash from any branch

- scanner.py
removed retries, attempts = 0, 0
f string fixed
removed unused variable lift_speed from run_probe
removed unused speed variable
removes un-used samples variable
removed unused import adc_temperature
> Chore: removed random useless code

- firmware.sh
> Use firmware flasher to flash from any branch (#86)

- scanner.py
Fixes the Z offset calibration bug.
> Fix: z offset issue

- scanner.py
> fix: z offset bug (#102)

- scanner.py
Changes the ghastly float to int so no more integer on output
> Fix change max_retries float to int

- scanner.py
Removes random duplicate line from `SCANNER_TOUCH` function
> remove duplicate line

- scanner.py
Fixes K series issues on develop
> removes graph generation and imports

- scanner.py
> Chore: Removed unused ADXL functions and variables

- scanner.py
- typings/clocksync.pyi
- typings/configfile.pyi
- typings/klippy.pyi
- typings/mcu.pyi
> Check firmware version before homing (#112)

- .github/workflows/pull-request.yml
- ci/k1-requirements.txt
- ci/standard-requirements.txt
- pyproject.k1.toml
- pyproject.toml
- requirements.txt
- scanner.py
This should check our python code against the k1 environment I received from @pellcorp 
> feat: setup ci to check k1 environment

- scanner.py
This will validate the loaded model's mode during homing.
> Validate model mode

- scanner.py
> Chore: More code cleanup

- __init__.py
- scanner.py
- typings/axis_twist_compensation.pyi
- typings/bed_mesh.pyi
- typings/clocksync.pyi
- typings/configfile.pyi
- typings/exclude_object.pyi
- typings/gcode.pyi
- typings/gcode_move.pyi
- typings/heaters.pyi
- typings/homing.pyi
- typings/kinematics/extruder.pyi
- typings/kinematics/none.pyi
- typings/klippy.pyi
- typings/manual_probe.pyi
- typings/mcu.pyi
- typings/msgproto.pyi
- typings/pins.pyi
- typings/probe.pyi
- typings/reactor.pyi
- typings/stepper.pyi
- typings/temperature_sensor.pyi
- typings/thermistor.pyi
- typings/toolhead.pyi
- typings/webhooks.pyi
Adds a lot of types. There's three refactoring of actual code:
- For probing, I removed a list we never used anywhere. https://github.com/Cartographer3D/cartographer-klipper/pull/139/commits/119f8ed1bb32d02657a2dc06fca4984b5e493f0e#diff-421942804459cec21567bdeaf1d73dfd6d1c68d6553f422e8f87d191d75a75f4L1318-R1316
- For `exclude_object` I moved the check into the shrink function, and refactored it https://github.com/Cartographer3D/cartographer-klipper/pull/139/commits/3bfb257eb3e17da18ded792bc0f340bf503d6312#diff-421942804459cec21567bdeaf1d73dfd6d1c68d6553f422e8f87d191d75a75f4L3259-R3324
- For `axis_twist_compensation` I got rid of the "weird" class and just passed the relevant function along https://github.com/Cartographer3D/cartographer-klipper/pull/139/commits/e56adf3ad940ff3d720e8a6b92548 …
> Add types for modules

- scanner.py
Chris' sleepiness seems to have dripped into code
> fix: fuzzy is not sleepy (#145)

- scanner.py
* formats for some reason
* fixes random nozzle touch message
> Fix text bug calibrate (#152)

- scanner.py
> chore: fix formatting

- scanner.py
Use an enum for `trigger_method`. Makes the code easier to understand.
> feat: use an enum for trigger_method

- scanner.py
> Implement probe get_status

- scanner.py
> Implement probe get_status (#156)

- scanner.py
This adds the anchor element around our macros so that they become clickable.
> feat: make macros clickable in console

- scanner.py
> Add model required to  threshold_scan

- scanner.py
> Better mcu identify error

- scanner.py
> Beta history into develop

- scanner.py
> Move only once

- scripts/firmware.py
> [FirmwareFlasher] Change text from find to select firmware

- scripts/firmware.py
> [FirmwareFlasher] Updates Katapult and Checks Origin

- scripts/firmware.py
Loops until device is found OR any key is pressed
> [FirmwareFlasher] Query DFU Device Inf Loop + Anykey Exit

- scripts/firmware.cfg
- scripts/firmware.py
> Merge Develop into Beta

- scripts/firmware.py
> [FirmwareFlasher] Repository would error when case-sensitive - 0.0.4

- scripts/firmware.py
> [FirmwareFlasher] Adds Advanced Menu for All Firmware

- scripts/firmware.py
> [FirmwareFlasher] Fixes klippy env path

- scripts/firmware.py
> [FirmwareFlasher] fixes klippy env path (#206)

- scanner.py
- typings/kinematics/none.pyi
- typings/toolhead.pyi
> Fix homing on newer klipper versions

- .github/workflows/pull-request.yml
- scanner.py
- scripts/firmware.py
- typings/kinematics/none.pyi
- typings/mcu.pyi
- typings/toolhead.pyi
Release current develop to beta
> Release to beta test

- scanner.py
Fixes the latest script breaking changes from latest Klipper release
> Fixed for latest Klipper changes
