.github/release-drafter.yml, .github/workflows/release-drafter.yml
Should allow us to make better use of the moonraker update channel.
Currently only maintains one draft, as `release-drafter` does not seem to be able to differentiate.
I will look into adding that functionality in their application, but this should at least help us get started.
With this change we can ask our users to set `channel: beta` and it should automatically use the tag of the newest published release.
To target the users on `channel: stable` we would have to mark a release as not pre-release and "latest".
`channel: dev` will, as now, pull latest commit from master - we should move the general users away from this.
Example: https://github.com/Jomik/release-drafter-test/releases
=> Implement automatic release drafting

scanner.py
Adjusted default scanner max_retries from 5 to 10.
Signed-off-by: Chris Krause <krause384@gmail.com>
=> Fix: adjusted max retries from 5 to 10

scanner.py
Changed probing speed of initial touch move to match the follow-up speeds.
Signed-off-by: Chris Krause <krause3284@gmail.com
=> fix: fixed threshold scan probing speed

scanner.py
Description
CARTOGRAPHER_TOUCH contained a syntax error that has now been resolved.
Signed-off-by: Chris Krause <[krause3284@gmail.com](mailto:krause3284@gmail.com)
=> fix: syntax error on retries

scanner.py
Moved output text from `CARTOGRAPHER_TOUCH` into debugging output instead.
**BEFORE**
**AFTER**
Signed-off-by: Chris Krause [krause3284@gmail.com](mailto:krause3284@gmail.com)
=> chore: moved various text from output to debugging

cartographer.py, scanner.py
Cartographer.py [cartographer] and Scanner.py [scanner] fixed models being saved to default when calling `CARTOGRAPHER_CALIBRATE` or `CARTOGRAPHER_TOUCH` and will now update based on currently loaded model, defaulting to default if no alternate model is in use.
Fixes Issue #13 
Signed-off-by: Chris Krause [krause3284@gmail.com](mailto:krause3284@gmail.com)
=> fix: updated cartographer.py and scanner.py to update current model

scanner.py
When adding MOVE=(x) to `CARTOGRAPHER_TOUCH` upon a retry attempt, the toolhead will randomly pick a new location to touch based on a random number between -(x) and +(x) for both the x and y axis
Example: `CARTOGRAPHER_TOUCH MOVE=6` will randomly choose locations between the centre of the bed +-6 on X and Y resulting in toolhead potentially moving by +X2.75 -Y5.35 before touching again.
Issue #35 
Signed-off-by: Chris Krause <[krause3284@gmail.com](mailto:krause3284@gmail.com)
=> feat: `MOVE` added to `CARTOGRAPHER_TOUCH`

scanner.py
When performing a `CARTOGRAPHER_TOUCH CALIBRATE=1` z offset will no longer be applied prior to calibration. This should fix any weird z_offset stacking issues.
Fixes Issue #51 
Signed-off-by: Chris Krause [krause3284@gmail.com](mailto:krause3284@gmail.com)
=> fix: when calibrating dont apply any z offset

scanner.py
Brings `CARTOGRAPHER_THRESHOLD_SCAN` into line with `CARTOGRAPHER_TOUCH`
Based on KrauTech-Nightly with improvements.
Maintains same command params from previous iteration for backwards compatibility.
=> Improved Threshold Scan, Touch and other small fixes

scanner.py
Will update or save `scanner_touch_speed` upon saving threshold if SPEED=x wasnt same as configured.
=> fix: save speed upon threshold save

scanner.py
Re-added missing imports for debugging graph generation
import csv
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.ticker import FuncFormatter
=> fix: missing imports

scanner.py
Quick change i pulled from KrauTech V2 that stops users setting offset below 0 and tells them to check calibration etc.
=> Fix: stops users setting offet below 0

scanner.py
Adds mode to models as well as renames and remaps associates commands with fallbacks.
`[scanner]`
- renamed `calibration_method` to `mode` (calibration_method is still available)
`[scanner model NAME]`
- added `model_mode: scan/touch` (based on whether youre using touch or not)
`PROBE_SWITCH` will now change what mode you're in, either scan or touch and will ask you to `SAVE_CONFIG` in order to update `mode` under [scanner]
**Previous:** `CARTOGRAPHER_TOUCH CALIBRATE=1` (still works)
**Now:** `CARTOGRAPHER_CALIBRATE`
---------------------------
**Previous:** `CARTOGRAPHER_TOUCH METHOD=manual` (still works)
**Now:** `CARTOGRAPHER_CALIBRATE METHOD=manual`
=> Feature: model mode switching & command update

firmware.sh
Firmware.sh to use same katapult script for USB as CAN. Fixes "CAN Flash Successul" when flashing via USB.
Line change
`~/klippy-env/bin/python ~/klipper/lib/canboot/flash_can.py -f $firmwareFile -d /dev/serial/by-id/$usbID`
to 
`python3 ~/katapult/scripts/flash_can.py -f $firmwareFile -d /dev/serial/by-id/$usbID`
=> fix: flashing via usb fixed to not say CAN Flash Success

scanner.py
Rewrote lambda expression as def.
=> chore: rewrote lambda as def

scanner.py
This adds a config option to set a default value for `MOVE`.
=> Make MOVE argument configurable

DEVELOPMENT.md, cartographer_ci_test.cfg
Should be explained in the change in [DEVELOPMENT.md](https://github.com/Cartographer3D/cartographer-klipper/blob/chore/ci-test-macro/DEVELOPMENT.md)
=> Create helper macro for integration testing

scanner.py, typings/configfile.pyi, typings/gcode.pyi, typings/klippy.pyi, typings/reactor.pyi
This creates types for `gcode` and `gcmd` variables.
The stubs are based off the code in https://github.com/Klipper3d/klipper/blob/f2e69a3703f97725fb0db626ff592a223e22b3a2/klippy/gcode.py
=> Add types for gcode and gcode command

.github/workflows/pull-request.yml, pyproject.toml, scanner.py, typings/mcu.pyi
We had an issue where we used 3.12 syntax in `scanner.py`, causing Klipper to fail on loading.
I thing 3.9 is a sane default for us.
=> fix: pin python version to 3.9

scanner.py
`tolerance` had become a tuple, woops.
=> fix: tolerance is not a tuple

scanner.py
fixes #110 as cur_temp > wait temp (155) instead of max temp 150
=> Fix PR #110 wait temp error

scanner.py, typings/clocksync.pyi, typings/configfile.pyi, typings/klippy.pyi, typings/mcu.pyi
Requires the user to recalibrate their model if it was made with a _different_ firmware version of the probe.
=> Check firmware version before homing

scanner.py, typings/gcode.pyi
Passes the params from `CARTOGRAPHER_CALIBRATE` onto the TOUCH function
=> Feature: pass params from calibrate to touch

scanner.py
Just removes unnecessary boilerplate to clean up the code a bit.
Also makes the construction explicit as there is a lot of positional arguments.
=> chore: make threshold result a dataclass

scanner.py, typings/gcode.pyi, typings/heater.pyi, typings/kinematics/extruder.pyi, typings/klippy.pyi, typings/toolhead.pyi
Just adds typing to the `lookup_object("toolhead")` call.
=> chore: add types for toolhead

scanner.py
=> Fix fuzzy touch name

scanner.py
=> fix: remove scanner.z_offset

scanner.py, typings/klippy.pyi, typings/quad_gantry_level.pyi, typings/z_tilt.pyi
And scans after all is homed, without any auto bed leveling in config..
=> feat: check bed leveling before threshold scan

scripts/README.md, scripts/firmware.py
A Python-based tool for managing and flashing firmware configurations for 3D printer setups. This script provides options to debug, select firmware versions, and handle configurations for CAN, USB, and DFU modes.
- **Interactive Menus:** Navigate through options with dynamic menus.
- **Debug Mode:** Enables detailed output for troubleshooting.
- **Firmware Selection:** Automatically retrieve and select firmware files based on device or user input.
- **Multi-mode Flashing:**
- CAN: Supports flashing devices over CAN.
- USB: Support for USB flashing.
- DFU: Support for DFU flashing (coming soon).
- **High-Temperature Firmware Support:** Search specifically for high-temperature configurations.
- **Katapult Support:** Includes integration with the Katapult tool for CAN device management.
- …
=> Firmware.py V0.0.1

scripts/firmware.py
Minor text fixes for firmware.py
=> minor text fixes

scripts/firmware.py
=> [FirmwareFlasher] fix -f arg not starting at that specific menu

scripts/firmware.py
=> [FirmwareFlasher] Move dfu flash to advanced menu

scripts/firmware.py
Had weird loop issues when trying to exit, realized id done self.menu calls when I shouldve done returns.
=> [FirmwareFlasher] Change Menu Calls to Returns

scripts/firmware.py
^ as title suggests. Open to thoughts.
=> [FirmwareFlasher] Adds logging

scripts/firmware.cfg, scripts/firmware.py
Allows users ability to edit directories for non standard installations. Includes defaults of 
- KLIPPY_LOG = ~/printer_data/logs/klippy.log
- KATAPULT_DIR = ~/katapult
- KLIPPER = ~/klipper
- KLIPPY_ENV = ~/klippy_env
File will be created and saved as firmware.cfg in the scripts folder if a user sets custom values from the menu.
=> [FirmwareFlasher] Adds Configuration file & Edit Menu + Minor Text Changes

.gitignore, scripts/firmware.py
As per title.
Removes .git from origin url to make sure all repos match whether they have .git or not in the url
=> [FirmwareFlasher] Normalise GIT repo origin

scripts/firmware.py
=> [FirmwareFlasher] Add LSUSB (/dev/ Directory to Config Options
